name = "wiki-telegram-bot"
main = "src/index.js"
compatibility_date = "2025-01-01"

[vars]
OWNER_USERNAME = "hamtik26kk"

# Создайте KV в Cloudflare (Workers & Pages → KV → Create) и вставьте его ID:
[[kv_namespaces]]
binding = "DB"
id = "6e9cb08dd8124e3d87ec37b250a15d74"
